// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartMetering.Metering.Infrastructure.Persistence;

#nullable disable

namespace SmartMetering.Metering.Infrastructure.Migrations
{
    [DbContext(typeof(MeteringDbContext))]
    partial class MeteringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartMetering.Metering.Domain.Readings.MeterReading", b =>
                {
                    b.Property<string>("MeterId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("meter_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Kwh")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("kwh");

                    b.HasKey("MeterId", "Timestamp");

                    b.ToTable("readings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
