apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-db
  labels:
    app: billing-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-db
  template:
    metadata:
      labels:
        app: billing-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "billing"
            - name: POSTGRES_PASSWORD
              value: "billing"
            - name: POSTGRES_DB
              value: "billing"
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: billing-db
spec:
  selector:
    app: billing-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
