apiVersion: apps/v1
kind: Deployment
metadata:
  name: meter-simulator
  labels:
    app: meter-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meter-simulator
  template:
    metadata:
      labels:
        app: meter-simulator
    spec:
      containers:
        - name: meter-simulator
          image: smartmetering-simulator:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: INGESTION_URL
              value: "http://ingestion:8080/readings" # gọi qua Service DNS trong cluster
            - name: METER_COUNT
              value: "5"
            - name: INTERVAL_SECONDS
              value: "5"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
